### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Demirrr**

### CODE REVIEW

**Comment by Demirrr** [comment]
@Jean-KOUAGOU Please work in this branch to refactor your data

**Comment by Demirrr** [comment]
https://github.com/dice-group/Ontolearn/issues/270 will be fixed in this branch by @Jean-KOUAGOU

**Comment by alkidbaci** [comment]
Well, the files are not being downloaded in the testing environment. If you check `tox.ini` line 19
`run_before = ./big_gitext/download_big.sh KGs/Mutagenesis/mutagenesis.owl` that's the only file being downloaded. Writing the shell commands directly in the .md file does not work. @Jean-KOUAGOU I suggest adding your files [here](https://hobbitdata.informatik.uni-leipzig.de/GitExt/OntoPy) and we can make use of the code inside `/big_gitext/download_big.sh`. Than we can adding the command inside `tox.ini` to download the files. This requires a .link file which i'm not sure where to find the metadata that should to be written there. An example for that is in the mutagenesis folder mentioned above. Or maybe there is a better solution, @Demirrr what do you think?

**Comment by Demirrr** [comment]
> > @alkidbaci @Jean-KOUAGOU I have been rethiking our strategy of using (1) tox.ini and (2) /big_gitext/download_big.sh
> > Maybe we should follow what we do in here => https://github.com/dice-group/dice-embeddings. Namely,
> > (1) Download data **wget https://hobbitdata.informatik.uni-leipzig.de/KG/KGs.zip && unzip KGs.zip** (2) Test only what is in the test folder **pytest -p no:warnings -x**
> 
> Should we do the changes for the testing before the new release?

Yes it makes sense!

**Pull request merged**
