### PR TITLE
OWL2SPARQL converter fixes

### PR DESCRIPTION
**Pull request by nkaralis**
This PR fixes some issues in the owl2sparql mapping

- the forAll operator (\forAll r.C)  now returns entities that do not have any pairs in the provided relationship
- fix in the negation
- cardinality restrictions (e.g., >= 2 r.C): for the <= operator the mapping now also returns entities that do not have any pairs in the provided relation (there are still some issues when the provided cardinality is 0 that need to be investigated)

This PR also introduces more test cases, comments and an option to restrict the entities returned by the query to be instances of owl:NamedIndividual

### CODE REVIEW

**Comment by Demirrr** [comment]
I found an error at the conversion

Given a concept as such,
`OWLObjectIntersectionOf((OWLObjectUnionOf((OWLClass(IRI('http://www.benchmark.org/family#','Mother')), OWLClass(IRI('http://www.benchmark.org/family#','Mother')))), OWLObjectIntersectionOf((OWLClass(IRI('http://www.benchmark.org/family#','Mother')), OWLClass(IRI('http://www.benchmark.org/family#','Mother'))))))`


```
Traceback (most recent call last):
    ....
    return self.converter.as_query("?var", c, False)
  File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 467, in as_query
    tp = self.convert(root_variable, ce)
  File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 104, in convert
    self.process(ce)
  File "/home/demir/anaconda3/envs/nrw/lib/python3.9/functools.py", line 938, in _method
    return method.__get__(obj, cls)(*args, **kwargs)
  File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 206, in _
    self.append(f"FILTER ( {v0} != {v1} )")
  File "/home/demir/anaconda3/envs/nrw/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 161, in intersection
    del self._intersection[self.modal_depth]
KeyError: 1
```

Do you have an idea @nkaralis @alkidbaci @SimonBin  :) ?

**Comment by alkidbaci** [comment]
> I found an error at the conversion
> 
> Given a concept as such, `OWLObjectIntersectionOf((OWLObjectUnionOf((OWLClass(IRI('http://www.benchmark.org/family#','Mother')), OWLClass(IRI('http://www.benchmark.org/family#','Mother')))), OWLObjectIntersectionOf((OWLClass(IRI('http://www.benchmark.org/family#','Mother')), OWLClass(IRI('http://www.benchmark.org/family#','Mother'))))))`
> 
> ```
> Traceback (most recent call last):
>     ....
>     return self.converter.as_query("?var", c, False)
>   File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 467, in as_query
>     tp = self.convert(root_variable, ce)
>   File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 104, in convert
>     self.process(ce)
>   File "/home/demir/anaconda3/envs/nrw/lib/python3.9/functools.py", line 938, in _method
>     return method.__get__(obj, cls)(*args, **kwargs)
>   File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 206, in _
>     self.append(f"FILTER ( {v0} != {v1} )")
>   File "/home/demir/anaconda3/envs/nrw/lib/python3.9/contextlib.py", line 126, in __exit__
>     next(self.gen)
>   File "/home/demir/Desktop/Softwares/NRW/owlapy/owl2sparql/converter.py", line 161, in intersection
>     del self._intersection[self.modal_depth]
> KeyError: 1
> ```
> 
> Do you have an idea @nkaralis @alkidbaci @SimonBin :) ?

Generated by the new code is the following: 

```
SELECT
 DISTINCT ?x WHERE { 
?x <http://dl-learner.org/carcinogenesis#hasBond> ?s_1 . 
{
{ SELECT ?s_1 WHERE { 
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_2 . 
 } GROUP BY ?s_1 HAVING ( COUNT ( ?s_2 ) <= 4 ) }
} UNION {
?s_1 ?s_3 ?s_4 . 
FILTER NOT EXISTS { 
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_5 . 
 } }
{ SELECT ?s_1 WHERE { 
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_6 . 
 } GROUP BY ?s_1 HAVING ( COUNT ( ?s_6 ) >= 1 ) }
 }
```
 
 Generated by the previous code: 
 
```
 SELECT
 DISTINCT ?x WHERE {
?x <http://dl-learner.org/carcinogenesis#hasBond> ?s_1 .
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_2 .
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_3 .
 }
GROUP BY ?x
 HAVING (
COUNT ( ?s_2 ) <= 4 && COUNT ( ?s_3 ) >= 1
 )
```

**Comment by alkidbaci** [comment]
Can you please confirm which is correct for the given concept:

```
prop_s = OWLObjectProperty(IRI.create("http://dl-learner.org/carcinogenesis#hasBond"))
        ce = OWLObjectSomeValuesFrom(
            prop_s,
            OWLObjectIntersectionOf((
                OWLObjectMaxCardinality(
                    4,
                    OWLObjectProperty(IRI.create("http://dl-learner.org/carcinogenesis#hasAtom")),
                    OWLThing
                ),
                OWLObjectMinCardinality(
                    1,
                    OWLObjectProperty(IRI.create("http://dl-learner.org/carcinogenesis#hasAtom")),
                    OWLThing
                )
            ))
        )
```

SPARQL query using the new code is as follows:

```
SELECT
 DISTINCT ?x WHERE { 
?x <http://dl-learner.org/carcinogenesis#hasBond> ?s_1 . 
{
{ SELECT ?s_1 WHERE { 
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_2 . 
 } GROUP BY ?s_1 HAVING ( COUNT ( ?s_2 ) <= 4 ) }
} UNION {
?s_1 ?s_3 ?s_4 . 
FILTER NOT EXISTS { 
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_5 . 
 } }
{ SELECT ?s_1 WHERE { 
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_6 . 
 } GROUP BY ?s_1 HAVING ( COUNT ( ?s_6 ) >= 1 ) }
 }
```

the query using the old code: 

```
SELECT
 DISTINCT ?x WHERE {
?x <http://dl-learner.org/carcinogenesis#hasBond> ?s_1 .
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_2 .
?s_1 <http://dl-learner.org/carcinogenesis#hasAtom> ?s_3 .
 }
GROUP BY ?x
 HAVING (
COUNT ( ?s_2 ) <= 4 && COUNT ( ?s_3 ) >= 1
 )
```

**Comment by nkaralis** [comment]
I believe it's the updated one. The && operation is now a join based on the results returned by the subqueries. In the updated version, we also consider for the <= case the entities that have no atoms using the filter not exists in one of the union components. 

My focus was mostly on ALC, so please, correct me if i am wrong.

**Pull request merged**
